### ISSUE TITLE
Brother Node left and right = null => cannot read color of undefined

### ISSUE THREAD

**Issue by valoricDe** [alexbol99/flatten-interval-tree#2]
Hi, in the function delete_fixup at
```
// Go to cases 2..4
if (brother_node.left.color == RB_TREE_COLOR_BLACK &&
    brother_node.right.color == RB_TREE_COLOR_BLACK)
```
the brother_node has color 1 and a parent node but is otherwise is undefined or null
Do you have a idea how to fix this?

**Comment by valoricDe** [comment]
Could it be that you missed ```else (same as then clause with **“right”** and **“left”** exchanged)``` in Cormen p. 326?

**Comment by alexbol99** [comment]
Hi, Velten @valoricDe 

Do you have a data to debug?

Thanks,
Alex Bol

**Comment by valoricDe** [comment]
Ohh, as I loged all the incoming nodes of delete_fixup I recognized that I used a reference to a internal node with a changed position in the tree, due to a former insert. I shouldn't have used the interla tree_delete function. I thought I could circumvent the additional tree_search.
Anyway, thank you for your implementation

**Comment by alexbol99** [comment]
Velten,
Thank you for your cooperation
