### ISSUE TITLE
Fast way to check if interval collides collides i.e intersects([low, high]): boolean

### ISSUE THREAD

**Issue by SudoPlz** [alexbol99/flatten-interval-tree#26]
Hey there,

I'm looking for a way to quickly tell if a given interval collides with even 1 of the existing intervals within a tree.
I assume `tree.search` keeps looking for **all** the other intervals within the input query interval (in order to return them), but I'm looking for a method that's faster than that, and just returns if it even encounters just 1 interval that collides with the input (query) interval.

Something like `tree.intersects([low, high]): boolean` 
Is there any way to do that (since I'm not interested about the values and I'm not interested in getting any of the intervals within the range, just the information of wether more than 1 exists or not).

I hope my question makes sense.

Thanks

**Comment by alexbol99** [comment]
Hi, @SudoPlz ,

Yes, it makes sense.
I will implement your request

**Comment by alexbol99** [comment]
Hi @SudoPlz ,

I added method ```intersect_any``` in version v1.0.14

Thank you for your contribution to this project,
Alex

**Comment by SudoPlz** [comment]
You're so kind. Thank you so much for adding that and for all your great work!
