### ISSUE TITLE
npm package size is too large (1.69MB) due to lack of proper .npmignore to exclude documentation files

### ISSUE THREAD

**Issue by chaudhryjunaid** [alexbol99/flatten-interval-tree#30]
Documentation for this module includes many font files and other miscellaneous files which are at this moment being published on npm along with the rest of the module. This leads to a size of 1.69MB of the unpacked module which is bad for two reasons:
1. projects including this module will have a larger footprint
2. initiates a distrust of this module as its functionality is not supposed to be so big that it is ~2MB in size
@alexbol99 I really appreciate what a wonderful and beautiful module this is. However, can you please add all irrelevant files to a .npmignore and publish a new version on npm so that published size is reduced.
Thanks, and Best Regards,

**Comment by alexbol99** [comment]
Thank you, @chaudhryjunaid for pointing me to this problem.
I added file  ```.npmignore``` where I ignored docs, test and example directories.
Package size of new version 2.0.15 is now 148 Kb.
Best regards,
Alex

**Comment by chaudhryjunaid** [comment]
Thanks! This helps, starting from my current project...
