### ISSUE TITLE
Question: are intervals returned by `search` sorted?

### ISSUE THREAD

**Issue by alamothe** [alexbol99/flatten-interval-tree#37]
Hello @alexbol99,
Thank you for this wonderful library. 

May I ask if we can assume that the intervals returned by `search` are sorted?

(I checked the docs, and prior issues before posting)

**Comment by alexbol99** [comment]
Hello, @alamothe 

The answer is "yes", interval tree is implemented as a binary tree, and search operation also performs traverse of the tree in an ordered way.

Thanks,
Alex

**Comment by alamothe** [comment]
Thank you!
